const OPENWEATHER_API_KEY="YOUR_OPENWEATHER_API_KEY";
const $=(id)=>document.getElementById(id);
const els={year:$('year'),app:$('app'),input:$('locationInput'),searchBtn:$('searchBtn'),geoBtn:$('geoBtn'),status:$('statusMessage'),locationName:$('locationName'),updatedTime:$('updatedTime'),alerts:$('alertsContainer'),saveFavoriteBtn:$('saveFavoriteBtn'),favoritesPanel:$('favoritesPanel'),favoritesList:$('favoritesList'),clearFavoritesBtn:$('clearFavoritesBtn'),currentTemp:$('currentTemp'),currentDescription:$('currentDescription'),currentIcon:$('currentIcon'),windValue:$('windValue'),humidityValue:$('humidityValue'),sunriseValue:$('sunriseValue'),sunsetValue:$('sunsetValue'),note:$('weathermanNote'),hourly:$('hourlyForecast'),daily:$('dailyForecast'),mapLayerSelect:$('mapLayerSelect'),vehicleGuidance:$('vehicleGuidance'),homeGuidance:$('homeGuidance'),outdoorGuidance:$('outdoorGuidance'),bestWindowGuidance:$('bestWindowGuidance')};
let currentPlace=null,map=null,marker=null,weatherLayer=null;
els.year.textContent=new Date().getFullYear();
document.addEventListener('DOMContentLoaded',()=>{if(window.feather)feather.replace();renderFavorites();});
els.searchBtn.addEventListener('click',()=>{const q=els.input.value.trim();if(!q)return setStatus('Please enter a ZIP code or city.',true);searchLocation(q);});
els.input.addEventListener('keydown',e=>{if(e.key==='Enter')els.searchBtn.click();});
els.geoBtn.addEventListener('click',()=>{if(!navigator.geolocation)return setStatus('Your browser does not support location lookup.',true);setStatus('Finding your location...');navigator.geolocation.getCurrentPosition(p=>loadWeather(p.coords.latitude,p.coords.longitude,'Your Location'),()=>setStatus('Location access was blocked. Try typing your ZIP or city.',true),{enableHighAccuracy:true,timeout:12000});});
els.saveFavoriteBtn.addEventListener('click',()=>{if(!currentPlace)return;const f=getFavorites();if(!f.some(i=>i.name===currentPlace.name)){f.push(currentPlace);localStorage.setItem('weathermanFavorites',JSON.stringify(f));}renderFavorites();setStatus(`${currentPlace.name} saved to My Favorite Places.`);});
els.clearFavoritesBtn.addEventListener('click',()=>{localStorage.removeItem('weathermanFavorites');renderFavorites();});
els.mapLayerSelect.addEventListener('change',updateWeatherLayer);
async function searchLocation(query){try{ensureApiKey();setStatus('Finding that location...');const cleaned=query.trim();if(/^\d{5}$/.test(cleaned)){const z=await lookupZip(cleaned);return loadWeather(z.lat,z.lon,z.name);}const url=`https://api.openweathermap.org/geo/1.0/direct?q=${encodeURIComponent(cleaned)}&limit=5&appid=${OPENWEATHER_API_KEY}`;const results=await fetchJson(url);if(!Array.isArray(results)||!results.length)return setStatus("I couldn't find that city. Try city + state, like Myrtle Beach, South Carolina.",true);const best=results.find(i=>i.country==='US')||results[0];const label=[best.name,best.state,best.country].filter(Boolean).join(', ');return loadWeather(best.lat,best.lon,label);}catch(e){console.error(e);setStatus(e.message||"I couldn't load that location. Try again.",true);}}
async function lookupZip(zip){try{const url=`https://api.openweathermap.org/geo/1.0/zip?zip=${encodeURIComponent(zip)},US&appid=${OPENWEATHER_API_KEY}`;const d=await fetchJson(url);if(d&&d.lat&&d.lon)return{lat:d.lat,lon:d.lon,name:d.name?`${d.name}, ${zip}`:zip};}catch(e){console.warn('OpenWeather ZIP lookup failed. Trying fallback.',e);}const fb=await fetchJson(`https://api.zippopotam.us/us/${encodeURIComponent(zip)}`);if(!fb||!fb.places||!fb.places.length)throw new Error("I couldn't find that ZIP code. Try city + state instead.");const p=fb.places[0];return{lat:Number(p.latitude),lon:Number(p.longitude),name:`${p['place name']}, ${p['state abbreviation']} ${zip}`};}
async function loadWeather(lat,lon,label){try{ensureApiKey();setStatus('Loading your local forecast...');const url=`https://api.openweathermap.org/data/3.0/onecall?lat=${lat}&lon=${lon}&exclude=minutely&units=imperial&appid=${OPENWEATHER_API_KEY}`;const data=await fetchJson(url);currentPlace={name:label,lat,lon,icon:conditionEmoji(data.current?.weather?.[0]?.main)};renderWeather(data,label);updateMap(lat,lon);els.app.classList.remove('hidden');setStatus('Forecast updated.');setTimeout(()=>window.scrollTo({top:els.app.offsetTop-18,behavior:'smooth'}),100);if(window.feather)feather.replace();}catch(e){console.error(e);setStatus(e.message||'Weather data is unavailable right now.',true);}}
function renderWeather(data,label){const c=data.current||{},w=c.weather?.[0]||{},tz=data.timezone;els.locationName.textContent=label;els.updatedTime.textContent=`Updated ${formatTime(c.dt,tz)}`;els.currentTemp.textContent=`${Math.round(c.temp)}°`;els.currentDescription.textContent=titleCase(w.description||'Current conditions');els.currentIcon.src=iconUrl(w.icon);els.currentIcon.alt=w.description||'Current weather';els.windValue.textContent=`${Math.round(c.wind_speed||0)} mph`;els.humidityValue.textContent=`${c.humidity??'--'}%`;els.sunriseValue.textContent=formatTime(c.sunrise,tz);els.sunsetValue.textContent=formatTime(c.sunset,tz);renderAlerts(data.alerts||[]);renderHourly(data.hourly||[],tz);renderDaily(data.daily||[],tz);renderNote(data);renderGuidance(data);}
function renderAlerts(alerts){els.alerts.innerHTML='';alerts.slice(0,3).forEach(a=>{const d=document.createElement('div');d.className='alert';d.innerHTML=`<strong>${escapeHtml(a.event||'Weather Alert')}</strong><br>${escapeHtml(a.description||'').slice(0,280)}...`;els.alerts.appendChild(d);});}
function renderHourly(hours,tz){els.hourly.innerHTML='';hours.slice(0,12).forEach(h=>{const w=h.weather?.[0]||{},pop=Math.round((h.pop||0)*100),card=document.createElement('div');card.className='hour-card';card.innerHTML=`<p>${formatHour(h.dt,tz)}</p><img src="${iconUrl(w.icon)}" alt="${escapeHtml(w.description||'Weather')}"/><strong>${Math.round(h.temp)}°</strong><p>${pop}% rain</p>`;els.hourly.appendChild(card);});}
function renderDaily(days,tz){els.daily.innerHTML='';days.slice(0,7).forEach(day=>{const w=day.weather?.[0]||{},card=document.createElement('div');card.className='day-card';card.innerHTML=`<strong>${formatDay(day.dt,tz)}</strong><img src="${iconUrl(w.icon)}" alt="${escapeHtml(w.description||'Weather')}"/><p>${titleCase(w.description||'Forecast')}</p><span class="temp-range">${Math.round(day.temp.max)}° / ${Math.round(day.temp.min)}°</span>`;els.daily.appendChild(card);});}
function renderNote(data){const c=data.current||{},temp=Math.round(c.temp||0),wind=c.wind_speed||0,hours=data.hourly?.slice(0,10)||[],rain=Math.max(0,...hours.map(h=>h.pop||0)),condition=c.weather?.[0]?.main||'weather';if(data.alerts?.length)els.note.textContent='Pay attention today. There is an active weather alert nearby, so check timing before travel or outdoor plans.';else if(rain>=.55)els.note.textContent=`It is ${temp}° now, and rain chances become meaningful today. Keep an umbrella handy and watch road conditions.`;else if(wind>=24)els.note.textContent=`It is ${temp}° with noticeable wind. Secure loose outdoor items and expect rougher highway driving.`;else if(temp>=90)els.note.textContent=`It is ${temp}° and heat is the main story. Plan water, shade, and breaks if you're outside.`;else if(temp<=35)els.note.textContent=`It is ${temp}° and cold enough to slow down a bit. Watch for slick spots if moisture is nearby.`;else els.note.textContent=`It is ${temp}° with ${condition.toLowerCase()} conditions. Overall, this looks like a manageable weather day.`;}
function renderGuidance(data){const c=data.current||{},hours=data.hourly?.slice(0,12)||[],rain=Math.max(0,...hours.map(h=>h.pop||0)),wind=c.wind_speed||0,temp=c.temp||0,alerts=Boolean(data.alerts?.length);els.vehicleGuidance.textContent=alerts||rain>.55?'Plan for wet roads. Check wipers, tire pressure, and leave extra stopping distance.':wind>22?'Gusty conditions may make highway driving feel rough. Watch crosswinds.':'Good basic travel window. Still check fuel, tires, and washer fluid.';els.homeGuidance.textContent=alerts?'Weather alerts are active. Secure loose outdoor items and keep phones charged.':wind>24?'Bring in lightweight patio items and anything that could blow around.':'No major home prep concerns showing right now.';els.outdoorGuidance.textContent=rain>.5?'Keep an indoor backup plan. Rain chances rise during the next several hours.':temp>90?'Hot conditions. Plan shade, water, and breaks.':temp<38?'Cold enough to bundle up. Watch slick spots if moisture arrives.':'Outdoor plans look reasonable based on the next few hours.';els.bestWindowGuidance.textContent=bestWindow(hours,data.timezone);}
function bestWindow(hours,tz){if(!hours.length)return'Hourly forecast is limited right now.';const best=hours.map(h=>({h,score:(h.pop||0)*80+Math.abs((h.temp||70)-72)*1.1+(h.wind_speed||0)*.75})).sort((a,b)=>a.score-b.score)[0].h;return`Best nearby window appears around ${formatHour(best.dt,tz)} with ${Math.round(best.temp)}° and ${Math.round((best.pop||0)*100)}% rain chance.`;}
function updateMap(lat,lon){if(!window.L)return;if(!map){map=L.map('weatherMap',{scrollWheelZoom:false}).setView([lat,lon],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);}else map.setView([lat,lon],8);if(marker)map.removeLayer(marker);marker=L.marker([lat,lon]).addTo(map);updateWeatherLayer();setTimeout(()=>map.invalidateSize(),250);}
function updateWeatherLayer(){if(!map)return;if(weatherLayer)map.removeLayer(weatherLayer);const layer=els.mapLayerSelect.value||'precipitation_new';weatherLayer=L.tileLayer(`https://tile.openweathermap.org/map/${layer}/{z}/{x}/{y}.png?appid=${OPENWEATHER_API_KEY}`,{attribution:'&copy; OpenWeather',opacity:.62});weatherLayer.addTo(map);}
function getFavorites(){try{return JSON.parse(localStorage.getItem('weathermanFavorites'))||[]}catch{return[]}}
function renderFavorites(){const f=getFavorites();els.favoritesList.innerHTML='';if(!f.length){els.favoritesPanel.classList.add('hidden');return}els.favoritesPanel.classList.remove('hidden');f.forEach(fav=>{const b=document.createElement('button');b.className='favorite-chip';b.type='button';b.innerHTML=`${fav.icon||'🌤️'} ${escapeHtml(fav.name)}`;b.addEventListener('click',()=>loadWeather(fav.lat,fav.lon,fav.name));els.favoritesList.appendChild(b);});}
async function fetchJson(url){const r=await fetch(url);if(!r.ok){if(r.status===401)throw new Error('OpenWeather API key issue. Make sure your real key is pasted into script.js.');throw new Error('That weather lookup failed. Try city + state.');}return r.json();}
function ensureApiKey(){if(!OPENWEATHER_API_KEY||OPENWEATHER_API_KEY==='YOUR_OPENWEATHER_API_KEY')throw new Error('Paste your OpenWeather API key into script.js first.');}
function setStatus(m,e=false){els.status.textContent=m;els.status.style.color=e?'#b42318':'';}
function iconUrl(icon){return`https://openweathermap.org/img/wn/${icon||'01d'}@2x.png`}
function conditionEmoji(main){const v=String(main||'').toLowerCase();if(v.includes('thunder'))return'⛈️';if(v.includes('rain')||v.includes('drizzle'))return'🌧️';if(v.includes('snow'))return'❄️';if(v.includes('cloud'))return'☁️';if(v.includes('clear'))return'☀️';if(v.includes('fog')||v.includes('mist'))return'🌫️';return'🌤️'}
function formatTime(ts,tz){if(!ts)return'--';return new Intl.DateTimeFormat('en-US',{timeZone:tz||undefined,hour:'numeric',minute:'2-digit'}).format(new Date(ts*1000));}
function formatHour(ts,tz){return new Intl.DateTimeFormat('en-US',{timeZone:tz||undefined,hour:'numeric'}).format(new Date(ts*1000));}
function formatDay(ts,tz){return new Intl.DateTimeFormat('en-US',{timeZone:tz||undefined,weekday:'short'}).format(new Date(ts*1000));}
function titleCase(v){return String(v).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1):'').join(' ')}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
